// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesHobbyProject.Models;

namespace MoviesHobbyProject.Migrations
{
    [DbContext(typeof(MemberMoviesContext))]
    partial class MemberMoviesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MoviesHobbyProject.Models.GroupMembers", b =>
                {
                    b.Property<int>("GroupMembersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberBio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupMembersID");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            GroupMembersID = 1,
                            FirstName = "Alainna",
                            LastName = "Nichols",
                            MemberBio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis a cras semper auctor neque vitae."
                        },
                        new
                        {
                            GroupMembersID = 2,
                            FirstName = "Martin",
                            LastName = "Dietal",
                            MemberBio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis a cras semper auctor neque vitae."
                        },
                        new
                        {
                            GroupMembersID = 3,
                            FirstName = "Saleem",
                            LastName = "Dweik",
                            MemberBio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis a cras semper auctor neque vitae."
                        },
                        new
                        {
                            GroupMembersID = 4,
                            FirstName = "Danielle",
                            LastName = "Maddux",
                            MemberBio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis a cras semper auctor neque vitae."
                        },
                        new
                        {
                            GroupMembersID = 5,
                            FirstName = "Vismaya",
                            LastName = "Manchaiah",
                            MemberBio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis a cras semper auctor neque vitae."
                        });
                });

            modelBuilder.Entity("MoviesHobbyProject.Models.MovieFavorites", b =>
                {
                    b.Property<int>("MovieFavoritesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GroupMembersID")
                        .HasColumnType("int");

                    b.Property<bool>("IsMovie")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("SavedMoviesID")
                        .HasColumnType("int");

                    b.HasKey("MovieFavoritesID");

                    b.HasIndex("GroupMembersID");

                    b.HasIndex("SavedMoviesID");

                    b.ToTable("Favorites");

                    b.HasData(
                        new
                        {
                            MovieFavoritesID = 1,
                            GroupMembersID = 1,
                            IsMovie = true,
                            Rating = 1,
                            SavedMoviesID = 1
                        },
                        new
                        {
                            MovieFavoritesID = 2,
                            GroupMembersID = 1,
                            IsMovie = true,
                            Rating = 1,
                            SavedMoviesID = 2
                        },
                        new
                        {
                            MovieFavoritesID = 3,
                            GroupMembersID = 1,
                            IsMovie = true,
                            Rating = 1,
                            SavedMoviesID = 3
                        },
                        new
                        {
                            MovieFavoritesID = 4,
                            GroupMembersID = 1,
                            IsMovie = true,
                            Rating = 1,
                            SavedMoviesID = 4
                        },
                        new
                        {
                            MovieFavoritesID = 5,
                            GroupMembersID = 1,
                            IsMovie = true,
                            Rating = 1,
                            SavedMoviesID = 5
                        },
                        new
                        {
                            MovieFavoritesID = 6,
                            GroupMembersID = 1,
                            IsMovie = true,
                            Rating = 1,
                            SavedMoviesID = 6
                        },
                        new
                        {
                            MovieFavoritesID = 7,
                            GroupMembersID = 1,
                            IsMovie = true,
                            Rating = 1,
                            SavedMoviesID = 7
                        },
                        new
                        {
                            MovieFavoritesID = 8,
                            GroupMembersID = 1,
                            IsMovie = true,
                            Rating = 1,
                            SavedMoviesID = 8
                        });
                });

            modelBuilder.Entity("MoviesHobbyProject.Models.SavedMovies", b =>
                {
                    b.Property<int>("SavedMoviesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("APIReferenceID")
                        .HasColumnType("int");

                    b.Property<string>("MovieName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SavedMoviesID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            SavedMoviesID = 1,
                            APIReferenceID = 8587,
                            MovieName = "The Lion King"
                        },
                        new
                        {
                            SavedMoviesID = 2,
                            APIReferenceID = 1726,
                            MovieName = "Iron Man"
                        },
                        new
                        {
                            SavedMoviesID = 3,
                            APIReferenceID = 10138,
                            MovieName = "Iron Man 2"
                        },
                        new
                        {
                            SavedMoviesID = 4,
                            APIReferenceID = 68721,
                            MovieName = "Iron Man 3"
                        },
                        new
                        {
                            SavedMoviesID = 5,
                            APIReferenceID = 136799,
                            MovieName = "Trolls"
                        },
                        new
                        {
                            SavedMoviesID = 6,
                            APIReferenceID = 10020,
                            MovieName = "Beauty and the Beast"
                        },
                        new
                        {
                            SavedMoviesID = 7,
                            APIReferenceID = 812,
                            MovieName = "Aladdin"
                        },
                        new
                        {
                            SavedMoviesID = 8,
                            APIReferenceID = 2493,
                            MovieName = "The Princess Bride"
                        });
                });

            modelBuilder.Entity("MoviesHobbyProject.Models.MovieFavorites", b =>
                {
                    b.HasOne("MoviesHobbyProject.Models.GroupMembers", "GroupMember")
                        .WithMany()
                        .HasForeignKey("GroupMembersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoviesHobbyProject.Models.SavedMovies", "MovieInfo")
                        .WithMany()
                        .HasForeignKey("SavedMoviesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
